steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/data-services/daas-securityxref.jar', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push','gcr.io/data-services/daas-securityxref.jar']